# -*- coding: utf-8 -*-
"""Copia de ActivationfunctionELU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EQp-VVwkV370h7DApfYvxVXywgs07FYP
"""

import numpy as np
alfa = 0.5
def ELU(x):
        if x>=0:
              return x
        else:
              return alfa*(np.exp(x)-1)

def perceptron(x, w, b):
        """ Function implemented by a perceptron with weight vecto w and bias """
        v=np.dot(w,x)+b
        y=ELU(v)
        return y

def NOT_percep(x):
      return perceptron(x, w=-1, b=0.5)

  # Test
print("NOT(0) = {}".format(NOT_percep(0)))
print("NOT(1) = {}".format(NOT_percep(1)))

def AND_percep(x):
  w = np.array([1, 1])
  b = -1.5
  return perceptron(x,w,b)

  # Test
example1 = np.array([1,1])
example2 = np.array([1,0])
example3 = np.array([0,1])
example4 = np.array([0,0])

print("AND({}, {}) = {}".format(1,1,AND_percep(example1)))
print("AND({}, {}) = {}".format(1,0,AND_percep(example2)))
print("AND({}, {}) = {}".format(0,1,AND_percep(example3)))
print("AND({}, {}) = {}".format(0,0,AND_percep(example4)))

def OR_percep(x):
    w = np.array([1,1])
    b = -0.5
    return perceptron(x, w, b)

#Test
example1 = np.array([1,1])
example2 = np.array([1,0])
example3 = np.array([0,1])
example4 = np.array([0,0])

print("OR({}, {}) = {}".format(1,1.5,OR_percep(example1)))
print("OR({}, {}) = {}".format(1,0,OR_percep(example2)))
print("OR({}, {}) = {}".format(0,1,OR_percep(example3)))
print("OR({}, {}) = {}".format(0,0,OR_percep(example4)))

def XOR_percep(x):
  output_AND = AND_percep(x)
  output_NOT = NOT_percep(output_AND)
  output_OR = OR_percep(x)
  x_temp = np.array([output_NOT, output_OR])
  output_AND = AND_percep(x_temp)
  return output_AND

#Test
example1 = np.array([1,1])
example2 = np.array([1,0])
example3 = np.array([0,1])
example4 = np.array([0,0])

print("XOR({}, {}) = {}".format(1,1,XOR_percep(example1)))
print("XOR({}, {}) = {}".format(1,0,XOR_percep(example2)))
print("XOR({}, {}) = {}".format(0,1,XOR_percep(example3)))
print("XOR({}, {}) = {}".format(0,0,XOR_percep(example4)))

def XNOR_percep(x):
  output_AND = AND_percep(x)
  output_NOT1 = NOT_percep(x[0])
  output_NOT2 = NOT_percep(x[1])
  output_NOT_AND = AND_percep(np.array([output_NOT1, output_NOT2]))
  x_temp = np.array([output_AND, output_NOT_AND])
  output_OR = OR_percep(x_temp)
  return output_OR


#Test
example1 = np.array([1,1])
example2 = np.array([1,0])
example3 = np.array([0,1])
example4 = np.array([0,0])

print("XNOR({}, {}) = {}".format(1,1,XNOR_percep(example1)))
print("XNOR({}, {}) = {}".format(1,0,XNOR_percep(example2)))
print("XNOR({}, {}) = {}".format(0,1,XNOR_percep(example3)))
print("XNOR({}, {}) = {}".format(0,0,XNOR_percep(example4)))