# -*- coding: utf-8 -*-
"""ActivationfunctionUnitStep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mWjOOAlBp_26MbRPy0NQn-9rrgTN_FFl
"""

import numpy as np

def unit_step(v):
    """ Heavyside Step function. v must be scalar """
    if v >= 0:
      return 1
    else:
      return 0
def perceptron(x,w,b):
    """ Function implemented by a perceptron with weight vector w and bias b"""
    v = np.dot(w,x)+b
    y = unit_step(v)
    return y

def NOT_percep(x):
      return perceptron(x, w=-1, b=0.5)

  # Test
print("NOT(-10) = {}".format(NOT_percep(-10)))
print("NOT(10) = {}".format(NOT_percep(10)))

def AND_percep(x):
  w = np.array([1, 1])
  b = -1.5
  return perceptron(x,w,b)

  # Test
example1 = np.array([1,1])
example2 = np.array([0.75,0.75])
example3 = np.array([0,1])
example4 = np.array([0,0])

print("AND({}, {}) = {}".format(1,1,AND_percep(example1)))
print("AND({}, {}) = {}".format(1,0,AND_percep(example2)))
print("AND({}, {}) = {}".format(0,1,AND_percep(example3)))
print("AND({}, {}) = {}".format(0,0,AND_percep(example4)))

def OR_percep(x):
    w = np.array([1,1])
    b = -0.5
    return perceptron(x, w, b)

#Test
example1 = np.array([1,1])
example2 = np.array([1,0])
example3 = np.array([0,1])
example4 = np.array([0,0])

print("OR({}, {}) = {}".format(1,1,OR_percep(example1)))
print("OR({}, {}) = {}".format(1,0,OR_percep(example2)))
print("OR({}, {}) = {}".format(0,1,OR_percep(example3)))
print("OR({}, {}) = {}".format(0,0,OR_percep(example4)))

def XOR_percep(x):
  output_AND = AND_percep(x)
  output_NOT = NOT_percep(output_AND)
  output_OR = OR_percep(x)
  x_temp = np.array([output_NOT, output_OR])
  output_AND = AND_percep(x_temp)
  return output_AND

#Test
example1 = np.array([0.5,0.49])
example2 = np.array([1,1])
example3 = np.array([0,1])
example4 = np.array([0,0])

print("OR({}, {}) = {}".format(1,1,XOR_percep(example1)))
print("OR({}, {}) = {}".format(1,0,XOR_percep(example2)))
print("OR({}, {}) = {}".format(0,1,XOR_percep(example3)))
print("OR({}, {}) = {}".format(0,0,XOR_percep(example4)))

def XNOR_percep(x):
  output_AND = AND_percep(x)
  output_NOT1 = NOT_percep(x[0])
  output_NOT2 = NOT_percep(x[1])
  output_NOT_AND = AND_percep(np.array([output_NOT1, output_NOT2]))
  x_temp = np.array([output_AND, output_NOT_AND])
  output_OR = OR_percep(x_temp)
  return output_OR


#Test
example1 = np.array([1,1])
example2 = np.array([1,0])
example3 = np.array([0,1])
example4 = np.array([0,0])

print("OR({}, {}) = {}".format(1,1,XNOR_percep(example1)))
print("OR({}, {}) = {}".format(1,0,XNOR_percep(example2)))
print("OR({}, {}) = {}".format(0,1,XNOR_percep(example3)))
print("OR({}, {}) = {}".format(0,0,XNOR_percep(example4)))